### ISSUE TITLE
Cannot run unittest

### ISSUE THREAD

**Issue by lwnica** [be-a-step/millicord.py#5]
stack trace
```
$ python -m unittest discover
EE
======================================================================
ERROR: millicord (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: millicord
Traceback (most recent call last):
  File "<user_directory>\AppData\Local\Programs\Python\Python37\Lib\unittest\loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "<user_directory>\AppData\Local\Programs\Python\Python37\Lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "<project_path>\millicord.py\millicord\__init__.py", line 1, in <module>
    from .idol import generate_idol_folder
  File "<project_path>\millicord.py\millicord\idol.py", line 5, in <module>
    from .idol_modules import IdolModules
  File "<project_path>\millicord.py\millicord\idol_modules.py", line 3, in <module>
    from .modules.utils.module_base import IdolModuleBase, IdolModuleType
  File "<project_path>\millicord.py\millicord\modules\__init__.py", line 1, in <module>
    from .basic_module import *
  File "<project_path>\millicord.py\millicord\modules\basic_module.py", line 32, in <module>
    class MessageSenderBaseModule(IdolModuleBase):
  File "<project_path>\millicord.py\millicord\modules\basic_module.py", line 38, in MessageSenderBaseModule
    async def send_message(self, channel: Messageable, message_text: str, message_receivers: Optional[list, str, int] = None):
  File "<user_directory>\AppData\Local\Programs\Python\Python37\Lib\typing.py", line 251, in inner
    return func(*args, **kwds)
  File "<user_directory>\AppData\Local\Programs\Python\Python37\Lib\typing.py", line 354, in __getitem__
    arg = _type_check(parameters, "Optional[t] requires a single type.")
  File "<user_directory>\AppData\Local\Programs\Python\Python37\Lib\typing.py", line 139, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Optional[t] requires a single type. Got (<class 'list'>, <class 'str'>, <class 'int'>).


======================================================================
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "<user_directory>\AppData\Local\Programs\Python\Python37\Lib\unittest\loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "<user_directory>\AppData\Local\Programs\Python\Python37\Lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "<project_path>\millicord.py\tests\__init__.py", line 1
    from . import idol_setting_test.py
                                   ^
SyntaxError: invalid syntax
```

**Comment by lwnica** [comment]
Verified on https://github.com/be-a-step/millicord.py/pull/7
